"""Add last_seen_pdf_id, last_seen_test_id, last_seen_notification_id to Profile

Revision ID: 23166b665816
Revises: 23dd92a121ee
Create Date: 2025-06-26 00:49:14.445152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23166b665816'
down_revision = '23dd92a121ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_pdf_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_seen_test_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_seen_notification_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('last_seen_notification_id')
        batch_op.drop_column('last_seen_test_id')
        batch_op.drop_column('last_seen_pdf_id')

    # ### end Alembic commands ###
