"""Make roll_number unique per class, not globally

Revision ID: 39d040298944
Revises: add_seen_to_notifications
Create Date: 2025-07-01 14:55:54.122518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d040298944'
down_revision = 'add_seen_to_notifications'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('seen',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint('roll_number', type_='unique')
        batch_op.create_unique_constraint('uix_class_roll', ['student_class', 'roll_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint('uix_class_roll', type_='unique')
        batch_op.create_unique_constraint('roll_number', ['roll_number'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('seen',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
