"""Add pending_popup field to Profile model

Revision ID: 9f41621ce2a7
Revises: cf90f20ca95d
Create Date: 2025-06-26 13:19:50.069437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f41621ce2a7'
down_revision = 'cf90f20ca95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_popup', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('pending_popup')

    # ### end Alembic commands ###
