"""Add cloudinary_url field to PDF model

Revision ID: ac4625b082f6
Revises: 36e378e0d78d
Create Date: 2025-07-07 10:45:22.836905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac4625b082f6'
down_revision = '36e378e0d78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upi_setting_change_logs')
    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloudinary_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_profiles_reg_no'), type_='unique')
        batch_op.drop_column('reg_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_no', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_profiles_reg_no'), ['reg_no'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.drop_column('cloudinary_url')

    op.create_table('upi_setting_change_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('field_changed', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('old_value', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('new_value', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], name=op.f('upi_setting_change_logs_admin_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('upi_setting_change_logs_pkey'))
    )
    # ### end Alembic commands ###
