"""Add reg_no to Profile

Revision ID: ae4394dbfc65
Revises: dba1dc2a20ee
Create Date: 2025-07-01 20:12:16.499406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4394dbfc65'
down_revision = 'dba1dc2a20ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_no', sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint('uq_profiles_reg_no', ['reg_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint('uq_profiles_reg_no', type_='unique')
        batch_op.drop_column('reg_no')

    # ### end Alembic commands ###
