"""Add last_seen_personal_notification_id to Profile model

Revision ID: c9122d5cd95a
Revises: 237819d345d0
Create Date: 2025-06-29 13:49:40.504498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9122d5cd95a'
down_revision = '237819d345d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_fee_is_paid'))
        batch_op.drop_index(batch_op.f('idx_fee_month'))
        batch_op.drop_index(batch_op.f('idx_fee_user_id'))
        batch_op.drop_index(batch_op.f('idx_fee_user_month'))

    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_mark_test_id'))
        batch_op.drop_index(batch_op.f('idx_mark_user_id'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_notification_created_at'))
        batch_op.drop_index(batch_op.f('idx_notification_user_id'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_payment_fee_id'))
        batch_op.drop_index(batch_op.f('idx_payment_is_confirmed'))
        batch_op.drop_index(batch_op.f('idx_payment_method'))
        batch_op.drop_index(batch_op.f('idx_payment_user_id'))

    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_pdf_uploaded_at'))

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_personal_notification_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_profile_roll_number'))
        batch_op.drop_index(batch_op.f('idx_profile_student_class'))
        batch_op.drop_index(batch_op.f('idx_profile_user_id'))

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_test_date'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_email'))
        batch_op.drop_index(batch_op.f('idx_user_is_admin'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_email'), ['email'], unique=False)

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_test_date'), ['date'], unique=False)

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_profile_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_profile_student_class'), ['student_class'], unique=False)
        batch_op.create_index(batch_op.f('idx_profile_roll_number'), ['roll_number'], unique=False)
        batch_op.drop_column('last_seen_personal_notification_id')

    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_pdf_uploaded_at'), ['uploaded_at'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_payment_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_payment_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('idx_payment_is_confirmed'), ['is_confirmed'], unique=False)
        batch_op.create_index(batch_op.f('idx_payment_fee_id'), ['fee_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_notification_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_notification_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_mark_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_mark_test_id'), ['test_id'], unique=False)

    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_fee_user_month'), ['user_id', 'month'], unique=False)
        batch_op.create_index(batch_op.f('idx_fee_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_fee_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('idx_fee_is_paid'), ['is_paid'], unique=False)

    # ### end Alembic commands ###
